# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Lint and Test
on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint_and_test:
    name: lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.3.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"

      - name: Get dependencies
        run: |
          go mod download

      - name: run unit tests
        timeout-minutes: 10
        run: |
          go test -v ./...